jwt.secretKey=YOUR_SECRET_KEY
http.port=PROCESS_API_HTTP_PORT_NUMBER
http.database.port=DATABASE_API_HTTP_PORT_NUMBER
http.database.host=DATABASE_API_HOST_NAME
http.payment.host=PAYMENT_API_HOST_NAME
http.payment.port=PAYMENT_API_HTTP_PORT_NUMBER