{
  "headers": {
    "x-user-id": "B-467884",
    "cache-control": "no-cache",
    "postman-token": "72f85650-9057-4f97-b39b-8d795003b2d3",
    "content-type": "application/json",
    "content-length": "116",
    "host": "localhost:8082",
    "user-agent": "PostmanRuntime/2.5.2",
    "accept": "*/*",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/process/orders",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/orders",
  "listenerPath": "/process/*",
  "localAddress": "/127.0.0.1:8082",
  "relativePath": "/process/orders",
  "uriParams": {},
  "rawRequestUri": "/process/orders",
  "rawRequestPath": "/process/orders",
  "remoteAddress": "/127.0.0.1:52351",
  "requestPath": "/process/orders"
}