#%RAML 1.0
title: ecommerceSuiteProcessApi2

uses:
  library: fragments/library.raml

/auth:
  /register:
    post:
      body:
        application/json:
          library.postUsersRequestBody
  /login:
    post:
      body:
        application/json:
          library.postUserLoginRequestBody

/stores:
  post:
    body:
      application/json:
        library.postStoresRequestBody
  /{storeId}:
    /products:
      post:
        body:
          application/json:
            library.postProductRequestBody
        is: [library.userIdHeader]
      get:
    /verification:
      patch:
        body:
          application/json:
            properties:
              status:
                required: true
                type: string
                enum: [unverified, verified, rejected]
  /seller:
    get:
      is: [library.userIdHeader]
  /admin:
    get:
      is: [library.getStoresByVerificationStatus]
                
/products:
  get:
    is: [library.getProductsByFilters]
  /{productId}:
    get:   
    patch:
      body:
        application/json:
          library.patchProductRequestBody   
      is: [library.userIdHeader]
    delete:
      is: [library.userIdHeader]
    /restock:
      patch:
        body:
          application/json:
            properties:
              quantity:
                required: true
                type: number
                minimum: 1
        is: [library.userIdHeader]

/carts:
  post:
    is: [library.userIdHeader]
    body:
      application/json:
        library.postCartRequestBody
  get:
    is: [library.userIdHeader]
  delete:
    is: [library.userIdHeader]
  /{cartItemId}:
    delete:
      is: [library.userIdHeader]
    /quantity:
      patch:
        is: [library.userIdHeader]
        body:
          application/json:
            properties:
              quantity:
                required: true
                type: number
                minimum: 1


/admin:
  /setup:
    post:
      body:
        application/json:
          library.postAdminSetupRequestBody



/orders:
  post:
    is: [library.userIdHeader]
    body:
      application/json:
        library.postOrderRequestBody
  /seller:
    get:
      is: [library.userIdHeader]
  /buyer:
    get:
      is: [library.userIdHeader]
  /{orderId}:
    get:
      is: [library.userIdHeader]
    /cancellation:
      patch:
        is: [library.userIdHeader]          

        